NebulaFlowStaticBundle:
    resource: "@NebulaFlowStaticBundle/Controller/"
    type:     annotation
    prefix:   /

NebulaFlowJobBundle:
    resource: "@NebulaFlowJobBundle/Controller/"
    type:     annotation
    prefix:   /job

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
